routes/web.php
<?php
use App\InformUsers;
use Cartalyst\Sentinel\Laravel\Facades\Sentinel;
use Illuminate\Support\Facades\DB;
/*
use App\Http\Controllers\HomeController;
use App\Mail\ContactMail;
use illuminate\http\Request;

include_once 'web_builder.php';
*/
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
Clear Cache Commands
php artisan route:cache
php artisan cache:clear
php artisan config:cache
php artisan view:clear
php artisan optimize

*/

Route::pattern('slug', '[a-z0-9- _]+');

Route::get("/email", function() {
    Mail::raw('Now I know how to send emails with Laravel', function($message)
     {
         $message->subject('Hi There!!');
         $message->from(config('mail.from.address'), config("app.name"));
         $message->to('jbcapucao265@gmail.com');
     });
 });


//PRC
Route::resource('parentresponsibilitycenter','PRCController');
Route::get('parentresponsibilitycenter/{id}/remove',
            ['uses' => 'PRCController@deletePRC'
            ])->name('parentresponsibilitycenter.remove');

//Allotment Class
Route::resource('allotmentclass','AllotmentClassController');
Route::get('allotmentclass/{id}/remove',
            ['uses' => 'AllotmentClassController@deleteAC'
            ])->name('allotmentclass.remove');

//Funding Cluster
Route::resource('fundcluster','FundClusterController');
Route::get('fundcluster/{id}/remove',
            ['uses' => 'FundClusterController@deleteFC'
            ])->name('fundcluster.remove');

//MFO-PAP
Route::resource('mfopap','MfoPapController');
Route::get('mfopap/{id}/remove',
            ['uses' => 'MfoPapController@deleteMP'
            ])->name('mfopap.remove');
//RC
Route::resource('responsibilitycenter','RCController');
Route::get('responsibilitycenter/{id}/remove',
            ['uses' => 'RCController@deleteRCCode'])->name('rc.remove');

//Payee
Route::resource('payee','PayeeController');
Route::get('payee/{id}/remove',
            ['uses' => 'PayeeController@deletePayee'])->name('payee.remove');

//PAC
Route::resource('parentaccountcode','ParentAccountCodeController');
Route::get('parentaccountcode/{id}/remove',
            ['uses' => 'ParentAccountCodeController@deletePAC'])->name('pac.remove');

//AC
Route::resource('accountcode','AccountCodeController');
Route::get('accountcode/{id}/remove',
            ['uses' => 'AccountCodeController@deleteACCode'])->name('ac.remove');
Route::get('reports',
            ['uses' => 'AccountCodeController@printPDF'])->name('printPDF');


//Budget Request
Route::resource('budget','ClaimsHeaderController');
Route::get('/ac', 'ClaimsHeaderController@ac');
Route::get('/printBurs/{id}',
            ['uses' => 'ClaimsHeaderController@bursPdf']);


# jbc addeds
Route::resource('released','ReleasedController');
Route::resource('received','ReceivedController');
Route::get('onroute','TrackDocumentController@onroute')->name('onroute');
Route::get('vfiled','TrackDocumentController@vfiled')->name('vfiled');

Route::resource('documentstracking','DocumentsTrackingController');
Route::get('documentstracking/{id}/remove',
            ['uses' => 'DocumentsTrackingController@deleteDoc'])->name('documentstracking.remove');

Route::resource('doctype','DocumentTypesController');
Route::resource('purpose','PurposesController');
Route::get('purpose/{id}/remove',
            ['uses' => 'PurposesController@deleteDTCode'])->name('purpose.remove');

//notification of
Route::get('informuser','InformUserController@index');
Route::post('informuser','InformUserController@store')->name('informuser');
Route::get('informuser/{id}','InformUserController@update')->name('informuser');

/*view Compose*/
View::composer(['*'], function($view) {
    if($userInfos = Sentinel::check()){
        $offices = DB::table('users')
        ->join('responsibility_centers', 'responsibility_centers.id', '=', 'users.rc_id')
        ->select('responsibility_centers.rc_description as rc_description')
        ->where('users.id', $userInfos->id)
        ->get();
        $notifs = InformUsers::where('to_rc_id', $userInfos->rc_id)->whereNull('is_read')->get();
        $allnotifs = InformUsers::where('to_rc_id', $userInfos->rc_id)->orderBy('created_at','desc')->get();
        $view->with('notifs', $notifs)->with('userInfo',$userInfos)
        ->with('offices', $offices)
        ->with('allnotifs',$allnotifs);
    }
});

Route::get('/', 'HomeController@showHome')->name('home');

Route::get('aboutus','HomeController@showAboutUs')->name('aboutus');

Route::get('contact','ContactFormController@create')->name('contact');
Route::post('contact','ContactFormController@store')->name('contact');

Route::get('timeline','HomeController@showTimeline')->name('timeline');
Route::get('timeline/trace','DocumentLogController@index')->name('trace');


// VuePress Documentation Route
Route::get('/docs/{file?}', 'VueControllerForm@index')->name('docs.index');

# Lock screen
Route::get('{id}/lockscreen', 'UsersController@lockscreen')->name('lockscreen');
Route::post('{id}/lockscreen', 'UsersController@postLockscreen')->name('lockscreen');

# All basic routes defined here
Route::get('login', 'AuthController@getSignin')->name('login');
Route::get('signin', 'AuthController@getSignin')->name('signin');
Route::post('signin', 'AuthController@postSignin')->name('postSignin');
Route::post('signup', 'AuthController@postSignup')->name('signup');
Route::post('forgot-password', 'AuthController@postForgotPassword')->name('signup');

# Forgot Password Confirmation
Route::get('forgot-password/{userId}/{passwordResetCode}', 'AuthController@getForgotPasswordConfirm')->name('forgot-password-confirm');
Route::post('forgot-password/{userId}/{passwordResetCode}', 'AuthController@getForgotPasswordConfirm');

# Logout
Route::get('logout', 'AuthController@getLogout')->name('logout');

# Account Activation
Route::get('activate/{userId}/{activationCode}', 'AuthController@getActivate')->name('activate');
//});


Route::group([ 'middleware' => 'admin'], function () {
    # Dashboard / Index
    Route::get('index', 'JoshController@showHome')->name('dashboard');
    Route::post('store', 'JoshController@showStore')->name('dashboard.store');

    # crop demo
    Route::post('crop_demo', 'JoshController@crop_demo')->name('crop_demo');
    # Activity log
    Route::get('activity_log', 'JoshController@ActivityLog')->name('activity_log');
    Route::get('task/data', 'TaskController@data')->name('data');
    # User Management

    Route::group([ 'prefix' => 'users'], function () {
        Route::get('data', 'UsersController@data')->name('users.data');
        Route::get('{user}/delete', 'UsersController@destroy')->name('users.delete');
        Route::get('{user}/confirm-delete', 'UsersController@getModalDelete')->name('users.confirm-delete');
        Route::get('{user}/restore', 'UsersController@getRestore')->name('restore.user');
        Route::post('{user}/passwordreset', 'UsersController@passwordreset')->name('passwordreset');
    });
    Route::resource('users', 'UsersController');

    Route::get('deleted_users',['before' => 'Sentinel', 'uses' => 'UsersController@getDeletedUsers'])->name('deleted_users');

    # Group Management
    Route::group(['prefix' => 'groups'], function () {
        Route::get('{group}/delete', 'GroupsController@destroy')->name('groups.delete');
        Route::get('{group}/confirm-delete', 'GroupsController@getModalDelete')->name('groups.confirm-delete');
        Route::get('{group}/restore', 'GroupsController@getRestore')->name('groups.restore');
    });
    Route::resource('groups', 'GroupsController');

    Route::get('{name?}', 'JoshController@showView');

});

# Remaining pages will be called from below controller method
# in real world scenario, you may be required to define all routes manually

Route::get('activate/{userId}/{activationCode}','FrontEndController@getActivate')->name('activate');
Route::get('forgot-password','FrontEndController@getForgotPassword')->name('forgot-password');
Route::post('forgot-password', 'FrontEndController@postForgotPassword');

# Forgot Password Confirmation
Route::post('forgot-password/{userId}/{passwordResetCode}', 'FrontEndController@postForgotPasswordConfirm');
Route::get('forgot-password/{userId}/{passwordResetCode}', 'FrontEndController@getForgotPasswordConfirm')->name('forgot-password-confirm');

app/Http/Controllers/RCController.php
<?php

namespace App\Http\Controllers;
use App\ResponsibilityCenter;
use App\ParentResponsibilityCenter;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\DB;
use Session;
use DataTables;

class RCController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = DB::table('responsibility_centers')
                ->join('parent_responsibility_centers', 'parent_responsibility_centers.id', '=', 'responsibility_centers.prc_id')
                ->select('responsibility_centers.id as id', 'responsibility_centers.rc_code as rc_code', 'responsibility_centers.rc_description as rc_description',
                        'parent_responsibility_centers.prc_code as prc_code', 'responsibility_centers.created_at as created_at', 'responsibility_centers.updated_at as updated_at')
                ->where('responsibility_centers.is_deleted', '<>', '1')->orderBy('responsibility_centers.id', 'ASC')->get();

        $prcs = DB::table('parent_responsibility_centers')
                    ->select('id', 'prc_code')
                    ->where('is_deleted', '<>', '1')->orderBy('prc_code', 'ASC')->get();
                    
        if (request()->ajax()){
            return Datatables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function($row){

                    $btn = '<a href="javascript:void(0)" data-toggle="tooltip"  data-id="'.$row->id.'" data-original-title="Edit" class="edit btn btn-primary btn-sm editRC">Edit</a>';

                    $btn = $btn.' <a href="javascript:void(0)" data-toggle="tooltip"  data-id="'.$row->id.'" data-original-title="Delete" class="btn btn-danger btn-sm deleteRC">Delete</a>';

                        return $btn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }

        return view('rc.child.index', compact('prcs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = \Validator::make($request->all(), [
            'prc_code' => 'required',
            'rc_code' => 'required|min:3',
            'rc_description' => 'required',
        ]);

            if ($validator->fails())
            {
                return response()->json(['errors'=>$validator->errors()->all()]);
            }

            if($request->status == "create"){
                if(ResponsibilityCenter::where([
                                    ['rc_code', '=', $request->rc_code],
                                    ['prc_id', '=', $request->prc_code],
                                    ['is_deleted', '<>', '1']
                                    ])->exists()){
                                        return response()->json(['code'=>'1']);
                }else{
                    ResponsibilityCenter::updateOrCreate(['id' => $request->id],
                                                ['prc_id' => $request->prc_code,
                                                'rc_code' => $request->rc_code,
                                                'rc_description' => $request->rc_description,
                                                'is_deleted' => '0']);
                }
            }elseif($request->status == "edit"){
                if(ResponsibilityCenter::where([
                                    ['id', '=', Input::get('id')],
                                    ['rc_code', '=', Input::get('rc_code')],
                                    ['prc_id', '=', Input::get('prc_code')],
                                    ['is_deleted', '<>', '1']
                                    ])->exists()){
                                        ResponsibilityCenter::find(Input::get('id'))
                                                    ->update(['rc_description' => $request->rc_description,
                                                            'rc_code' => $request->rc_code,
                                                            'prc_id' => $request->prc_code,
                                                            'is_deleted' => '0']);
                }else{
                    if(ResponsibilityCenter::where([
                                        ['id', '=', Input::get('id')],
                                        ['rc_code', '=', Input::get('rc_code')],
                                        ['prc_id', '=', Input::get('prc_code')],
                                        ['is_deleted', '<>', '1']
                                        ])->exists()){
                                            return response()->json(['code'=>'1']);
                    }else{
                        ResponsibilityCenter::find(Input::get('id'))
                                        ->update(['rc_code' => $request->rc_code,
                                                'rc_description' => $request->rc_description,
                                                'prc_id' => $request->prc_code,
                                                'is_deleted' => '0']);
                    }
                    
                }
            }

        return response()->json(['success'=>$request->status]);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = DB::table('responsibility_centers')
                ->join('parent_responsibility_centers', 'parent_responsibility_centers.id', '=', 'responsibility_centers.prc_id')
                ->select('responsibility_centers.id as id', 'responsibility_centers.rc_code as rc_code', 'responsibility_centers.rc_description as rc_description',
                'parent_responsibility_centers.id as prc_id', 'parent_responsibility_centers.prc_code as prc_code', 'responsibility_centers.created_at as created_at', 'responsibility_centers.updated_at as updated_at')
                ->where('responsibility_centers.id', '=', $id)->where('responsibility_centers.is_deleted', '<>', '1')->orderBy('responsibility_centers.id', 'ASC')->get();

        return response()->json($data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

    }

    public function deleteRCCode($id)
    {
        ResponsibilityCenter::updateOrCreate(['id' => $id],
                                    ['is_deleted' => '1']);

        return response()->json(['successfully deleted']);
    }


}

resources/views/rc/parent/index.blade.php
@extends('layouts/default')
{{-- Page title --}}
@section('title')
Parent Responsibility Centers
@parent
@stop

{{-- page level styles --}}
@section('header_styles')
<link rel="stylesheet" type="text/css" href="{{ asset('vendors/datatables/css/dataTables.bootstrap4.css') }}" />
<link href="{{ asset('css/pages/tables.css') }}" rel="stylesheet" type="text/css" />
@stop


{{-- Page content --}}
@section('content')
<section class="content-header">
    <h1>Parent Responsibility Centers</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('dashboard') }}">
                <i class="livicon" data-name="home" data-size="14" data-color="#000"></i>
                Dashboard
            </a>
        </li>
        <li><a href="#"> Parent Responsibility Centers</a></li>
        <li class="active">PRC List</li>
    </ol>
</section>

<!-- Main content -->
<section class="content paddingleft_right15">
    <div class="row">
        <div class="col-12">
        <div class="card panel-primary ">
            <div class="card-heading">
            <span><a class="btn btn-success btn-sm float-left" href="javascript:void(0)" id="createNewPRCCode">New Parent Responsibility Center</a></span>   
            <div class="pull-right">
            <div class="card-title pull-right"> <i class="livicon" data-name="list" data-size="16" data-loop="true" data-c="#fff" data-hc="white"></i>
                    PRC List
            </div>
            </div>
            </div>
            <div class="card-body">
                <div class="table-responsive-lg table-responsive-sm table-responsive-md">
                <table class="table table-bordered width100" id="prcdatatable">
                                <thead>
                                    <tr class="filters">
                                        <th>#</th>
                                        <th>PRCCode</th>
                                        <th>PRCDescription</th>
                                        <th>Generated</th>
                                        <th>Last Update</th>
                                        <th width="280px">Action</th>
                                    </tr>
                                </thead>
                                <tbody>

                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th>#</th>
                                        <th>PRCCode</th>
                                        <th>PRCDescription</th>
                                        <th>Generated</th>
                                        <th>Last Update</th>
                                        <th width="280px">Action</th>
                                    </tr>
                                </tfoot>
                </table>
                </div>

            </div>
        </div>

            <div class="modal fade" id="ajaxModel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="alert alert-danger" style="display:none"></div>
                        <div class="modal-header">
                            <h4 class="modal-title" id="modelHeading"></h4>
                        </div>


                        <div class="card-body">
                            <form id="prcForm" name="prcForm" class="form-horizontal">
                                <input type="hidden" name="id" id="id">
                                <input type="hidden" name="status" id="status">
                                <div class="form-group row">
                                    <label for="fname" class="col-sm-3 text-right control-label col-form-label">PRC Code*</label>
                                    <div class="col-sm-9">
                                        <input type="text" name="prc_code" class="form-control" id="prc_code" placeholder="PRC Code Here">
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="lname" class="col-sm-3 text-right control-label col-form-label">PRC Description*</label>
                                    <div class="col-sm-9">
                                        <input type="text" name="prc_description" class="form-control" id="prc_description" placeholder="PRC Description Here">
                                    </div>
                                </div>

                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-primary" id="saveBtn" value="create">Save changes</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@stop

{{-- page level scripts --}}
@section('footer_scripts')
    <script type="text/javascript" src="{{ asset('vendors/datatables/js/jquery.dataTables.js') }}" ></script>
    <script type="text/javascript" src="{{ asset('vendors/datatables/js/dataTables.bootstrap4.js') }}" ></script>
    <script>
        jQuery(function() {
            jQuery.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': jQuery('meta[name="csrf-token"]').attr('content')
                }
            });
        });

            var table = jQuery('#prcdatatable').DataTable({
                processing: true,
                serverSide: true,
                ajax: {
                    'url':"{{ route('parentresponsibilitycenter.index') }}",
                    'type': 'GET',
                    'headers': {
                    'X-CSRF-TOKEN': '{{ csrf_token() }}'
                    }
                },
                orderCellsTop: true,
                fixedHeader: true,
                columns: [
                        {data: 'id', name: 'id'},
                        {data: 'prc_code', name: 'prc_code'},
                        {data: 'prc_description', name: 'prc_description'},
                        {data: 'created_at', name: 'created_at'},
                        {data: 'updated_at', name: 'updated_at'},
                        {data: 'action', name: 'action', orderable: false, searchable: false},
                    ],
            order: [[0, 'desc']]
            });

            jQuery('#createNewPRCCode').click(function () {
                jQuery('#saveBtn').val("create-prccode");
                jQuery('#id').val('');
                jQuery('#status').val('create');
                jQuery('#prcForm').trigger("reset");
                jQuery('#modelHeading').html("Create New Parent Responsibility Center");
                jQuery('#ajaxModel').modal('show');
                jQuery('.alert-danger').hide();
            });

            jQuery('body').on('click', '.editPRCCode', function () {
                var prccode_id = jQuery(this).data('id');
                jQuery.get("{{ route('parentresponsibilitycenter.index') }}" +'/' + prccode_id +'/edit', function (data) {
                    jQuery('#modelHeading').html("Edit Parent Responsibility Center");
                    jQuery('#saveBtn').val("edit-user");
                    jQuery('#ajaxModel').modal('show');
                    jQuery('#saveBtn').html('Save changes');
                    jQuery('#id').val(data.id);
                    jQuery('#status').val('edit');
                    jQuery('#prc_code').val(data.prc_code);
                    jQuery('#prc_description').val(data.prc_description);
                })
            });

            jQuery('#saveBtn').click(function (e) {
                e.preventDefault();
                jQuery(this).html('Sending..');

                jQuery.ajax({
                data: jQuery('#prcForm').serialize(),
                url: "{{ route('parentresponsibilitycenter.store') }}",
                type: "POST",
                dataType: 'json',
                success: function (data) {
                    if(data.errors){
                  		jQuery('.alert-danger').html('');
                        jQuery('#saveBtn').html('Save changes');
                  		jQuery.each(data.errors, function(key, value){
                  			jQuery('.alert-danger').show();
                  			jQuery('.alert-danger').append('<li>'+value+'</li>');
                  		});

                  	}else if(data.code == "1"){
                        jQuery('.alert-danger').html('');
                        jQuery('#saveBtn').html('Save changes');
                        jQuery('.alert-danger').show();
                        jQuery('.alert-danger').append('<li>PRCCode Already Exists</li>');
                    }else{
                        jQuery('#prcForm').trigger("reset");
                        jQuery('#ajaxModel').modal('hide');
                        table.draw();
                  	}

                },
                error: function (data) {
                    console.log('Error:', data);
                    jQuery('#saveBtn').html('Save Changes');
                }
                });
            });

            jQuery('body').on('click', '.deletePRCCode', function () {
                var prccode_id = jQuery(this).data("id");
                    $.confirm({
                        theme: 'dark',
                        title: 'Please Confirm!',
                        content: 'Are you sure you want to delete this item PRCCode?',
                        buttons: {
                            confirm: function () {
                                $.ajax({
                                    type: "GET",
                                    url: "{{ route('parentresponsibilitycenter.index') }}" +'/' + prccode_id +'/remove',
                                    success: function(data){
                                        table.draw();
                                    },
                                    error: function(data){
                                        console.log('Error', data);
                                    }
                                });

                            },
                            cancel: function () {
                                // $.alert('Canceled!');
                            }
                        }
                    });               
            });
    </script>
@stop

@push('scripts')
    
@endpush