routes/web.php
<?php
use App\InformUsers;
use Cartalyst\Sentinel\Laravel\Facades\Sentinel;
use Illuminate\Support\Facades\DB;
/*
use App\Http\Controllers\HomeController;
use App\Mail\ContactMail;
use illuminate\http\Request;

include_once 'web_builder.php';
*/
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
Clear Cache Commands
php artisan route:cache
php artisan cache:clear
php artisan config:cache
php artisan view:clear
php artisan optimize

*/

Route::pattern('slug', '[a-z0-9- _]+');

Route::get("/email", function() {
    Mail::raw('Now I know how to send emails with Laravel', function($message)
     {
         $message->subject('Hi There!!');
         $message->from(config('mail.from.address'), config("app.name"));
         $message->to('jbcapucao265@gmail.com');
     });
 });


//PRC
Route::resource('parentresponsibilitycenter','PRCController');
Route::get('parentresponsibilitycenter/{id}/remove',
            ['uses' => 'PRCController@deletePRC'
            ])->name('parentresponsibilitycenter.remove');

//Allotment Class
Route::resource('allotmentclass','AllotmentClassController');
Route::get('allotmentclass/{id}/remove',
            ['uses' => 'AllotmentClassController@deleteAC'
            ])->name('allotmentclass.remove');

//Funding Cluster
Route::resource('fundcluster','FundClusterController');
Route::get('fundcluster/{id}/remove',
            ['uses' => 'FundClusterController@deleteFC'
            ])->name('fundcluster.remove');

//MFO-PAP
Route::resource('mfopap','MfoPapController');
Route::get('mfopap/{id}/remove',
            ['uses' => 'MfoPapController@deleteMP'
            ])->name('mfopap.remove');
//RC
Route::resource('responsibilitycenter','RCController');
Route::get('responsibilitycenter/{id}/remove',
            ['uses' => 'RCController@deleteRCCode'])->name('rc.remove');

//Payee
Route::resource('payee','PayeeController');
Route::get('payee/{id}/remove',
            ['uses' => 'PayeeController@deletePayee'])->name('payee.remove');

//PAC
Route::resource('parentaccountcode','ParentAccountCodeController');
Route::get('parentaccountcode/{id}/remove',
            ['uses' => 'ParentAccountCodeController@deletePAC'])->name('pac.remove');

//AC
Route::resource('accountcode','AccountCodeController');
Route::get('accountcode/{id}/remove',
            ['uses' => 'AccountCodeController@deleteACCode'])->name('ac.remove');
Route::get('reports',
            ['uses' => 'AccountCodeController@printPDF'])->name('printPDF');


//Budget Request
Route::resource('budget','ClaimsHeaderController');
Route::get('/ac', 'ClaimsHeaderController@ac');
Route::get('/printBurs/{id}',
            ['uses' => 'ClaimsHeaderController@bursPdf']);


# jbc addeds
Route::resource('released','ReleasedController');
Route::resource('received','ReceivedController');
Route::get('onroute','TrackDocumentController@onroute')->name('onroute');
Route::get('vfiled','TrackDocumentController@vfiled')->name('vfiled');

Route::resource('documentstracking','DocumentsTrackingController');
Route::get('documentstracking/{id}/remove',
            ['uses' => 'DocumentsTrackingController@deleteDoc'])->name('documentstracking.remove');

Route::resource('doctype','DocumentTypesController');
Route::resource('purpose','PurposesController');
Route::get('purpose/{id}/remove',
            ['uses' => 'PurposesController@deleteDTCode'])->name('purpose.remove');

//notification of
Route::get('informuser','InformUserController@index');
Route::post('informuser','InformUserController@store')->name('informuser');
Route::get('informuser/{id}','InformUserController@update')->name('informuser');

/*view Compose*/
View::composer(['*'], function($view) {
    if($userInfos = Sentinel::check()){
        $offices = DB::table('users')
        ->join('responsibility_centers', 'responsibility_centers.id', '=', 'users.rc_id')
        ->select('responsibility_centers.rc_description as rc_description')
        ->where('users.id', $userInfos->id)
        ->get();
        $notifs = InformUsers::where('to_rc_id', $userInfos->rc_id)->whereNull('is_read')->get();
        $allnotifs = InformUsers::where('to_rc_id', $userInfos->rc_id)->orderBy('created_at','desc')->get();
        $view->with('notifs', $notifs)->with('userInfo',$userInfos)
        ->with('offices', $offices)
        ->with('allnotifs',$allnotifs);
    }
});

Route::get('/', 'HomeController@showHome')->name('home');

Route::get('aboutus','HomeController@showAboutUs')->name('aboutus');

Route::get('contact','ContactFormController@create')->name('contact');
Route::post('contact','ContactFormController@store')->name('contact');

Route::get('timeline','HomeController@showTimeline')->name('timeline');
Route::get('timeline/trace','DocumentLogController@index')->name('trace');


// VuePress Documentation Route
Route::get('/docs/{file?}', 'VueControllerForm@index')->name('docs.index');

# Lock screen
Route::get('{id}/lockscreen', 'UsersController@lockscreen')->name('lockscreen');
Route::post('{id}/lockscreen', 'UsersController@postLockscreen')->name('lockscreen');

# All basic routes defined here
Route::get('login', 'AuthController@getSignin')->name('login');
Route::get('signin', 'AuthController@getSignin')->name('signin');
Route::post('signin', 'AuthController@postSignin')->name('postSignin');
Route::post('signup', 'AuthController@postSignup')->name('signup');
Route::post('forgot-password', 'AuthController@postForgotPassword')->name('signup');

# Forgot Password Confirmation
Route::get('forgot-password/{userId}/{passwordResetCode}', 'AuthController@getForgotPasswordConfirm')->name('forgot-password-confirm');
Route::post('forgot-password/{userId}/{passwordResetCode}', 'AuthController@getForgotPasswordConfirm');

# Logout
Route::get('logout', 'AuthController@getLogout')->name('logout');

# Account Activation
Route::get('activate/{userId}/{activationCode}', 'AuthController@getActivate')->name('activate');
//});


Route::group([ 'middleware' => 'admin'], function () {
    # Dashboard / Index
    Route::get('index', 'JoshController@showHome')->name('dashboard');
    Route::post('store', 'JoshController@showStore')->name('dashboard.store');

    # crop demo
    Route::post('crop_demo', 'JoshController@crop_demo')->name('crop_demo');
    # Activity log
    Route::get('activity_log', 'JoshController@ActivityLog')->name('activity_log');
    Route::get('task/data', 'TaskController@data')->name('data');
    # User Management

    Route::group([ 'prefix' => 'users'], function () {
        Route::get('data', 'UsersController@data')->name('users.data');
        Route::get('{user}/delete', 'UsersController@destroy')->name('users.delete');
        Route::get('{user}/confirm-delete', 'UsersController@getModalDelete')->name('users.confirm-delete');
        Route::get('{user}/restore', 'UsersController@getRestore')->name('restore.user');
        Route::post('{user}/passwordreset', 'UsersController@passwordreset')->name('passwordreset');
    });
    Route::resource('users', 'UsersController');

    Route::get('deleted_users',['before' => 'Sentinel', 'uses' => 'UsersController@getDeletedUsers'])->name('deleted_users');

    # Group Management
    Route::group(['prefix' => 'groups'], function () {
        Route::get('{group}/delete', 'GroupsController@destroy')->name('groups.delete');
        Route::get('{group}/confirm-delete', 'GroupsController@getModalDelete')->name('groups.confirm-delete');
        Route::get('{group}/restore', 'GroupsController@getRestore')->name('groups.restore');
    });
    Route::resource('groups', 'GroupsController');

    Route::get('{name?}', 'JoshController@showView');

});

# Remaining pages will be called from below controller method
# in real world scenario, you may be required to define all routes manually

Route::get('activate/{userId}/{activationCode}','FrontEndController@getActivate')->name('activate');
Route::get('forgot-password','FrontEndController@getForgotPassword')->name('forgot-password');
Route::post('forgot-password', 'FrontEndController@postForgotPassword');

# Forgot Password Confirmation
Route::post('forgot-password/{userId}/{passwordResetCode}', 'FrontEndController@postForgotPasswordConfirm');
Route::get('forgot-password/{userId}/{passwordResetCode}', 'FrontEndController@getForgotPasswordConfirm')->name('forgot-password-confirm');

app/Payee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Payee extends Model
{
    protected $guarded = [];
    public $table = "payees";
    protected $fillable = ['id', 'signatory_name', 'signatory_designation','address', 'email_address',
                            'rc_id','is_signatory', 'is_deleted', 'created_at', 'updated_at'];
}

app/Http/Controllers/PayeeController.php
<?php

namespace App\Http\Controllers;

use App\Payee;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\DB;
use Session;
use DataTables;

class PayeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = DB::table('payees')
                ->join('responsibility_centers', 'responsibility_centers.id', '=', 'payees.rc_id')
                ->select('payees.id as id', 'payees.signatory_name as sign_name', 'payees.signatory_designation as sign_designation',
                        'payees.address as address', 'payees.email_address as email_address', 'responsibility_centers.rc_description as rc_description',
                        'payees.created_at as created_at', 'payees.updated_at as updated_at')
                ->where('payees.is_deleted', '<>', '1')->orderBy('payees.id', 'ASC')->get();

        $rcs = DB::table('responsibility_centers')
            ->select('id', 'rc_description')
            ->where('is_deleted', '<>', '1')->orderBy('rc_description', 'ASC')->get();

        if (request()->ajax()){
            return Datatables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function($row){

                    $btn = '<a href="javascript:void(0)" data-toggle="tooltip"  data-id="'.$row->id.'" data-original-title="Edit" class="edit btn btn-primary btn-sm editPayee">Edit</a>';

                    $btn = $btn.' <a href="javascript:void(0)" data-toggle="tooltip"  data-id="'.$row->id.'" data-original-title="Delete" class="btn btn-danger btn-sm deletePayee">Delete</a>';

                        return $btn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }

        return view('payee.index', compact('rcs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = \Validator::make($request->all(), [
            'sign_name' => 'required|min:3',
            'sign_designation' => 'required|min:3',
            'address' => 'required|min:3',
            'email_address' => 'required|min:3|email',
            'rc_code' => 'required',
            'is_signatory' => 'required',
        ]);

            if ($validator->fails())
            {
                return response()->json(['errors'=>$validator->errors()->all()]);
            }

            if($request->status == "create"){
                if(Payee::where([
                                    ['signatory_name', '=', $request->sign_name],
                                    ['signatory_designation', '=', $request->sign_designation],
                                    ['is_deleted', '<>', '1']
                                    ])->exists()){
                                        return response()->json(['code'=>'1']);
                }else{
                    Payee::updateOrCreate(['id' => $request->id],
                                                ['signatory_name' => $request->sign_name,
                                                'signatory_designation' => $request->sign_designation,
                                                'address' => $request->address,
                                                'email_address' => $request->email_address,
                                                'rc_id' => $request->rc_code,
                                                'is_signatory' => $request->is_signatory,
                                                'is_deleted' => '0']);
                }
            }elseif($request->status == "edit"){
                if(Payee::where([
                                    ['id', '=', Input::get('id')],
                                    ['signatory_name', '=', Input::get('sign_name')],
                                    ['is_deleted', '<>', '1']
                                    ])->exists()){
                                        Payee::find(Input::get('id'))
                                                    ->update(['signatory_name' => $request->sign_name,
                                                            'signatory_designation' => $request->sign_designation,
                                                            'address' => $request->address,
                                                            'email_address' => $request->email_address,
                                                            'rc_id' => $request->rc_code,
                                                            'is_signatory' => $request->is_signatory,
                                                            'is_deleted' => '0']);
                }else{
                    if(Payee::where([
                                        ['id', '=', Input::get('id')],
                                        ['signatory_name', '=', Input::get('sign_name')],
                                        ['is_deleted', '<>', '1']
                                        ])->exists()){
                                            return response()->json(['code'=>'1']);
                    }else{
                        Payee::find(Input::get('id'))
                                        ->update(['signatory_name' => $request->sign_name,
                                                'signatory_designation' => $request->sign_designation,
                                                'address' => $request->address,
                                                'email_address' => $request->email_address,
                                                'rc_id' => $request->rc_code,
                                                'is_signatory' => $request->is_signatory,
                                                'is_deleted' => '0']);
                    }

                }
            }

        return response()->json(['success'=>$request->status]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Payee  $payee
     * @return \Illuminate\Http\Response
     */
    public function show(Payee $payee)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Payee  $payee
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = DB::table('payees')
                ->join('responsibility_centers', 'responsibility_centers.id', '=', 'payees.rc_id')
                ->select('payees.id as id', 'payees.signatory_name as sign_name', 'payees.signatory_designation as sign_designation',
                        'payees.address as address', 'payees.email_address as email_address', 'responsibility_centers.rc_description as rc_description',
                        'responsibility_centers.id as rc_id', 'payees.is_signatory as is_signatory', 'payees.created_at as created_at', 'payees.updated_at as updated_at')
                ->where('payees.id', '=', $id)->where('payees.is_deleted', '<>', '1')->orderBy('payees.id', 'ASC')->get();
        return response()->json($data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Payee  $payee
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Payee $payee)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Payee  $payee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Payee $payee)
    {
        //
    }

    public function deletePayee($id)
    {
        Payee::updateOrCreate(['id' => $id],
                                    ['is_deleted' => '1']);

        return response()->json(['successfully deleted']);
    }
}

resources/views/payee/index.blade.php
@extends('layouts/default')
{{-- Page title --}}
@section('title')
Payee
@parent
@stop

{{-- page level styles --}}
@section('header_styles')
<link rel="stylesheet" type="text/css" href="{{ asset('vendors/datatables/css/dataTables.bootstrap4.css') }}" />
<link href="{{ asset('css/pages/tables.css') }}" rel="stylesheet" type="text/css" />
@stop


{{-- Page content --}}
@section('content')
<section class="content-header">
    <h1>Contact Person</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('dashboard') }}">
                <i class="livicon" data-name="home" data-size="14" data-color="#000"></i>
                Dashboard
            </a>
        </li>
        <li><a href="#">Person In-charge</a></li>
        <li class="active">Personnels</li>
    </ol>
</section>

<!-- Main content -->
<section class="content paddingleft_right15">
    <div class="row">
        <div class="col-12">
        <div class="card panel-primary ">
            <div class="card-heading">
            <span><a class="btn btn-success btn-sm float-left" href="javascript:void(0)" id="createNewPayee">New Personnel</a></span>
            <div class="pull-right">
            <div class="card-title pull-right"> <i class="livicon" data-name="users" data-size="16" data-loop="true" data-c="#fff" data-hc="white"></i>
                    Personnel List
            </div>
            </div>
            </div>
            <div class="card-body">
                <div class="table-responsive-lg table-responsive-sm table-responsive-md">
                <table class="table table-bordered width100" id="signdatatable">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th width="180px">Name</th>
                                        <th width="180px">Designation</th>
                                        <th width="180px">Address</th>
                                        <th width="100px">Email Address</th>
                                        <th>Responsibility Center</th>
                                        <th>Generated</th>
                                        <th>Last Update</th>
                                        <th width="100px">Action</th>
                                    </tr>
                                </thead>
                                <tbody>

                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th>#</th>
                                        <th>Name</th>
                                        <th>Designation</th>
                                        <th>Address</th>
                                        <th>Email Address</th>
                                        <th>Responsibility Center</th>
                                        <th>Generated</th>
                                        <th>Last Update</th>
                                        <th width="280px">Action</th>
                                    </tr>
                                </tfoot>
                </table>
                </div>

            </div>
        </div>

        <div class="modal fade" id="ajaxModel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="alert alert-danger" style="display:none"></div>
                    <div class="modal-header">
                        <h4 class="modal-title" id="modelHeading"></h4>
                    </div>


                    <div class="card-body">
                        <form id="payeeForm" name="payeeForm" class="form-horizontal">
                            <input type="hidden" name="id" id="id">
                            <input type="hidden" name="status" id="status">
                            <div class="form-group row">
                                <label for="fname" class="col-sm-3 text-right control-label col-form-label">Name*</label>
                                <div class="col-sm-9">
                                    <input type="text" name="sign_name" class="form-control" id="sign_name" placeholder="Name Here">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="lname" class="col-sm-3 text-right control-label col-form-label">designation*</label>
                                <div class="col-sm-9">
                                    <input type="text" name="sign_designation" class="form-control" id="sign_designation" placeholder="designation Here">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="lname" class="col-sm-3 text-right control-label col-form-label">Address*</label>
                                <div class="col-sm-9">
                                    <input type="text" name="address" class="form-control" id="address" placeholder="Address Here">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="lname" class="col-sm-3 text-right control-label col-form-label">Email Address*</label>
                                <div class="col-sm-9">
                                    <input type="text" name="email_address" class="form-control" id="email_address" placeholder="Email Address Here">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-md-3 text-right control-label col-form-label">Responsibility Center</label>
                                <div class="col-md-9">
                                    <select class="select2 form-control custom-select" id="rc_code" name="rc_code" style="width: 100%; height:36px;">
                                        <option disabled>Select a RC Code</option>
                                        @foreach($rcs as $rc)
                                            <option value="{{ $rc->id }}">{{ $rc->rc_description }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-md-3 text-right control-label col-form-label">is Signatory?</label>
                                <div class="col-md-9">
                                    <select class="select2 form-control custom-select" id="is_signatory" name="is_signatory" style="width: 100%; height:36px;">
                                        <option value="1">Yes</option>
                                        <option value="0">No</option>
                                    </select>
                                </div>
                            </div>

                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-primary" id="saveBtn" value="create">Save changes</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        </div>
    </div>
</section>
@stop

{{-- page level scripts --}}
@section('footer_scripts')
    <script type="text/javascript" src="{{ asset('vendors/datatables/js/jquery.dataTables.js') }}" ></script>
    <script type="text/javascript" src="{{ asset('vendors/datatables/js/dataTables.bootstrap4.js') }}" ></script>
    <script>
        jQuery(function() {
            jQuery.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': jQuery('meta[name="csrf-token"]').attr('content')
                }
            });

            var table = jQuery('#signdatatable').DataTable({
                processing: true,
                serverSide: true,
                ajax: {
                    'url':"{{ route('payee.index') }}",
                    'type': 'GET',
                    'headers': {
                    'X-CSRF-TOKEN': '{{ csrf_token() }}'
                    }
                },
                orderCellsTop: true,
                fixedHeader: true,
                columns: [
                        {data: 'id', name: 'id'},
                        {data: 'sign_name', name: 'sign_name'},
                        {data: 'sign_designation', name: 'sign_designation'},
                        {data: 'address', name: 'address'},
                        {data: 'email_address', name: 'email_address'},
                        {data: 'rc_description', name: 'rc_description'},
                        {data: 'created_at', name: 'created_at'},
                        {data: 'updated_at', name: 'updated_at'},
                        {data: 'action', name: 'action', orderable: false, searchable: false},
                    ],
            order: [[0, 'desc']]
            });

            jQuery('#createNewPayee').click(function () {
                jQuery('#saveBtn').val("create-payee");
                jQuery('#id').val('');
                jQuery('#status').val('create');
                jQuery('#payeeForm').trigger("reset");
                jQuery('#modelHeading').html("Create New Payee");
                jQuery('#ajaxModel').modal('show');
                jQuery('.alert-danger').hide();
            });

            jQuery('body').on('click', '.editPayee', function () {
                var payee_id = jQuery(this).data('id');
                jQuery.get("{{ route('payee.index') }}" +'/' + payee_id +'/edit', function (data) {
                    jQuery('#modelHeading').html("Edit Payee");
                    jQuery('#saveBtn').val("edit-user");
                    jQuery('#ajaxModel').modal('show');
                    jQuery('#saveBtn').html('Save changes');
                    jQuery('#id').val(data[0].id);
                    jQuery('#status').val('edit');
                    jQuery('#sign_name').val(data[0].sign_name);
                    jQuery('#sign_designation').val(data[0].sign_designation);
                    jQuery('#address').val(data[0].address);
                    jQuery('#email_address').val(data[0].email_address);
                    jQuery('#rc_code').val(data[0].rc_id);
                    jQuery('#is_signatory').val(data[0].is_signatory);
                })
            });

            jQuery('#saveBtn').click(function (e) {
                e.preventDefault();
                jQuery(this).html('Sending..');

                jQuery.ajax({
                data: jQuery('#payeeForm').serialize(),
                url: "{{ route('payee.store') }}",
                type: "POST",
                dataType: 'json',
                success: function (data) {
                    if(data.errors){
                  		jQuery('.alert-danger').html('');
                        jQuery('#saveBtn').html('Save changes');
                  		jQuery.each(data.errors, function(key, value){
                  			jQuery('.alert-danger').show();
                  			jQuery('.alert-danger').append('<li>'+value+'</li>');
                  		});

                  	}else if(data.code == "1"){
                        jQuery('.alert-danger').html('');
                        jQuery('#saveBtn').html('Save changes');
                        jQuery('.alert-danger').show();
                        jQuery('.alert-danger').append('<li>Payee Already Exists</li>');
                    }else{
                        jQuery('#payeeForm').trigger("reset");
                        jQuery('#ajaxModel').modal('hide');
                        table.draw();
                  	}

                },
                error: function (data) {
                    console.log('Error:', data);
                    jQuery('#saveBtn').html('Save Changes');
                }
                });
            });

            jQuery('body').on('click', '.deletePayee', function () {
                var payee_id = jQuery(this).data("id");
                var s = confirm("Are you sure you want to delete this item Payee?");
                if(s){
                    $.ajax({
                        type: "GET",
                        url: "{{ route('payee.index') }}" +'/' + payee_id +'/remove',
                        success: function(data){
                            table.draw();
                        },
                        error: function(data){
                            console.log('Error', data);
                        }
                    });
                }

            });


        });
    </script>
@stop

@push('scripts')

@endpush